default:
    trainer: sac
    batch_size: 128
    buffer_size: 500000
    buffer_init_steps: 10000
    hidden_units: 256
    init_entcoef: 0.1
    learning_rate: 3.0e-4
    learning_rate_schedule: constant
    max_steps: 1.0e7
    memory_size: 256
    normalize: false
    num_update: 1
    train_interval: 4
    num_layers: 2
    time_horizon: 128
    sequence_length: 64
    summary_freq: 10000
    tau: 0.01
    use_recurrent: false
    vis_encode_type: simple
    reward_signals:
        extrinsic:
            strength: 2.0
            gamma: 0.99
        curiosity:
            strength: 0.02
            gamma: 0.95
            encoding_size: 256
